### ISSUE TITLE
Suggestion - rosin, clean, change strings, etc. 

### ISSUE THREAD

**Issue by prsley** [Poseidon-I/ling-ling#6]
I think it would be cool to add a "rosin", "clean", and "change strings" command. The "rosin" command will rosin your bow so you sound good when you practice, perform, and rehearse. If you don't rosin your bow daily, you won't make as much violins. The "clean" command is the same thing. The change strings command could have a cooldown of 6 months or something. I think it would also be cool to add titles like "conductor" or "first chair" after a achievement like "1,000,000 violins".

**Comment by strad-dev** [comment]
i guess i could make a sort of "clean" thing but there's rosin every time before you practise, which accounts for 10%, tuning before you practise, which accounts for 10%

and then there are things like wiping down your violin (20%) and unwinding your bow (15%) every day

and then every six months you need to change strings (45%)

so 10 + 10 + 20 + 15 + 45 = 100

**Comment by strad-dev** [comment]
maybe random events where your violin gets damaged or your string breaks and you have to take care of that, idk, I'm just throwing ideas around
either way its going to be a pain to update the saves bc idk how to iterate between files in folders which is why `!lb` is broken

**Comment by strad-dev** [comment]
suggestions have been move into support server #suggestions

**Comment by strad-dev** [comment]
oh hey i ended up doing this anyway lol
